[build.environment]
  NODE_VERSION = "20"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/2021/composable-vue/*"
  to = "/2021/composable-vue/index.html"
  status = 200

[[redirects]]
  from = "/2021/vueconf-china/*"
  to = "/2021/vueconf-china/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://antfu.me/talks"
  status = 302
